### ISSUE TITLE
Uninstall deletes whole plugins directory

### ISSUE THREAD

**Issue by macinspak** [pksunkara/electron-plugin-manager#80]
Hi, found a new one today. I am doing this:

```javascript
// In renderer process
ipcRenderer.on('epm-uninstalled-is-number', (event, err) => {
  // ...
});

ipcRenderer.send('epm-uninstall', dir, 'is-number');
// Response sent to `epm-uninstalled-${name}` channel where `name` is the plugin name
```
Exactly using that syntax, and my plugins directory is "plugins", and had other plugins in it. But this command deleted the entire plugs directory (and all plugins!).

**Comment by pksunkara** [comment]
I am unable to reproduce this. Did you send `ipcRenderer.send('epm-uninstall', dir, '')`? That would delete the whole plugins folder.
